name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install build dependencies
      run: sudo apt-get -qq update && sudo apt-get install -y build-essential meson appstream libtool itstool pkg-config intltool libicu-dev libpcre3-dev libglib2.0-dev libgtk-3-dev libxml2-utils
    - name: setup meson build config
      run: meson build
    - name: run meson build
      run: ninja -C build
    - name: run tests
      run: ninja -C build test
